# Generated by Django 3.1.7 on 2021-03-23 15:39

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=250)),
                ('course_description', models.TextField(blank=True)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultant_course', to='lms.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Course_module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_title', models.CharField(max_length=250)),
                ('module_description', models.TextField(blank=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_module', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='Course_quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=250)),
                ('quiz_description', models.TextField(blank=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz', to='lms.course_module')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.TextField()),
                ('question', models.TextField()),
                ('question_binary', models.BinaryField(blank=True)),
                ('difficulty', models.IntegerField()),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='lms.course_quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
                ('consultant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur', to='lms.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Course_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_title', models.TextField(blank=True)),
                ('content_image', models.ImageField(default=None, upload_to=lms.models.store_course_content)),
                ('content_video', models.FileField(default=None, upload_to=lms.models.store_course_content)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_content', to='lms.course_module')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.BinaryField(blank=True)),
                ('answer_par', models.TextField()),
                ('entr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entr_answer', to='lms.entrepreneur')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_name', to='lms.quiz_question')),
            ],
        ),
    ]
