# Generated by Django 3.1.7 on 2021-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_icon',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
