# Generated by Django 3.1.7 on 2021-04-15 09:59

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_course_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content',
            name='content_audio',
            field=models.FileField(default=None, upload_to=lms.models.store_course_content_audio),
        ),
        migrations.AlterField(
            model_name='course_content',
            name='content_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
