# Generated by Django 3.1.7 on 2021-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20210415_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content',
            name='content_text',
            field=models.TextField(blank=True),
        ),
    ]
